title: Mishrak - Portfolio
email: mishrak.dev@gmail.com
description: >-
  Professional portfolio showcasing cloud architecture and full-stack development projects.
  Cloud Solutions Architect & Full Stack Developer.
baseurl: "/portfolio"
url: "https://k5hitij.github.io"

# Social links
github_username: K5HITIJ
linkedin_username: mishrak
twitter_username: mishrak_dev

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO settings
lang: en_US
logo: /assets/images/logo.png
twitter:
  username: yourusername
  card: summary_large_image
facebook:
  app_id: 
  publisher: 
  admins: 

author:
  name: Mishrak
  email: mishrak@example.com
  twitter: yourusername

# Google Analytics
google_analytics: 

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - package.json
  - package-lock.json
  - webpack.config.js
  - .gitignore

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/
  blog:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Mishrak"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
    values:
      image: /assets/images/default-og-image.png

# Sass settings
sass:
  style: compressed

# Pagination
paginate: 6
paginate_path: "/blog/page:num/"
