apiVersion: v2
name: portfolio
description: A cloud-native portfolio website
type: application
version: 0.1.0
appVersion: "1.0.0"

keywords:
  - portfolio
  - web
  - cloud-native

home: https://yourdomain.com
sources:
  - https://github.com/yourusername/portfolio

maintainers:
  - name: Mishrak
    email: mishrak@example.com

dependencies:
  - name: nginx-ingress
    version: "4.7.1"
    repository: "https://kubernetes.github.io/ingress-nginx"
    condition: ingress.enabled
  - name: cert-manager
    version: "v1.12.0"
    repository: "https://charts.jetstack.io"
    condition: tls.enabled
